//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hrsw.XiAnPro.CMMClients.CalypsoServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalypsoRequest", Namespace="http://schemas.datacontract.org/2004/07/CalypsoServiceInterfaces")]
    [System.SerializableAttribute()]
    public partial class CalypsoRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Hrsw.XiAnPro.Models.Part PartField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Hrsw.XiAnPro.Models.Part Part {
            get {
                return this.PartField;
            }
            set {
                if ((object.ReferenceEquals(this.PartField, value) != true)) {
                    this.PartField = value;
                    this.RaisePropertyChanged("Part");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalypsoServiceReference.ICalypsoService")]
    public interface ICalypsoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalypsoService/MakeOffsetFile", ReplyAction="http://tempuri.org/ICalypsoService/MakeOffsetFileResponse")]
        bool MakeOffsetFile(Hrsw.XiAnPro.CMMClients.CalypsoServiceReference.CalypsoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalypsoService/MakeOffsetFile", ReplyAction="http://tempuri.org/ICalypsoService/MakeOffsetFileResponse")]
        System.Threading.Tasks.Task<bool> MakeOffsetFileAsync(Hrsw.XiAnPro.CMMClients.CalypsoServiceReference.CalypsoRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalypsoServiceChannel : Hrsw.XiAnPro.CMMClients.CalypsoServiceReference.ICalypsoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalypsoServiceClient : System.ServiceModel.ClientBase<Hrsw.XiAnPro.CMMClients.CalypsoServiceReference.ICalypsoService>, Hrsw.XiAnPro.CMMClients.CalypsoServiceReference.ICalypsoService {
        
        public CalypsoServiceClient() {
        }
        
        public CalypsoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalypsoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalypsoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalypsoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool MakeOffsetFile(Hrsw.XiAnPro.CMMClients.CalypsoServiceReference.CalypsoRequest request) {
            return base.Channel.MakeOffsetFile(request);
        }
        
        public System.Threading.Tasks.Task<bool> MakeOffsetFileAsync(Hrsw.XiAnPro.CMMClients.CalypsoServiceReference.CalypsoRequest request) {
            return base.Channel.MakeOffsetFileAsync(request);
        }
    }
}
